spring:
  application:
    name: er-alarm-backend
  profiles:
    active: local
    group:
      local:
        - common
      dev:
        - common
      prod:
        - common
  config:
    import:
      - classpath:/application-secret.yaml
---
spring:
  config:
    activate:
      on-profile: common
  # Database
  sql:
    init:
      platform: postgres
  datasource:
    driver-class-name: org.postgresql.Driver

  # jpa properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC+9
---
spring:
  config:
    activate:
      on-profile: local

  # PostgreSQL

  # RabbitMQ
  rabbitmq:
    template:
      exchange: test
      routing-key: test
      default-receive-queue: test